<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>DocumentNumber.Portugal.Nif.Generator</AssemblyName>
    <PackageId>DocumentNumber.Portugal.Nif.Generator</PackageId>
    <Title>DocumentNumber.Portugal.Nif.Generator</Title>
    <Description>A library that generates a valid NIF (tax payer id) for testing purposes.</Description>
    <PackageTags>Document Number Validation</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DocumentNumber.Portugal.Vat.Generator\DocumentNumber.Portugal.Vat.Generator.csproj" />
  </ItemGroup>

</Project>
