<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	  <AssemblyName>DocumentNumber.InternationalBankAccountNumber.Validator</AssemblyName>
    <PackageId>DocumentNumber.InternationalBankAccountNumber.Validator</PackageId>
    <Title>DocumentNumber.InternationalBankAccountNumber.Validator</Title>
    <Description>A library that validates if the International Bank Account number (IBAN) is valid or not.</Description>
    <PackageTags>Document Number Validation</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DocumentNumber.ValidatorAbstractions\DocumentNumber.ValidatorAbstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="iban-lengths.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>



</Project>
