<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<AssemblyName>DocumentNumber.Portugal.Nif.Validator</AssemblyName>
		<PackageId>DocumentNumber.Portugal.Nif.Validator</PackageId>
		<Title>DocumentNumber.Portugal.Nif.Validator</Title>
		<Description>A library that validates if the NIF (tax payer id) is valid or not.</Description>
		<PackageTags>Document Number Validation</PackageTags>
	</PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\DocumentNumber.Portugal.Nif.Generator\DocumentNumber.Portugal.Nif.Generator.csproj" />
    <ProjectReference Include="..\DocumentNumber.Portugal.Vat.Validator\DocumentNumber.Portugal.Vat.Validator.csproj" />
    <ProjectReference Include="..\DocumentNumber.ValidatorAbstractions\DocumentNumber.ValidatorAbstractions.csproj" />
  </ItemGroup>
</Project>