name: Build And Deploy all Libraries

on:
  push:    
    branches: 
      - 'release/all/**'

env:
  CONFIGURATION: 'Release'
  DOTNET_VERSION: '10.x'

jobs:
  build_and_test:
    runs-on: windows-latest

    steps:
      - name: Checkout.
        uses: actions/checkout@v4
      - name: Setup .NET.
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            6.x
            7.x
            8.x
            9.x
            10.x
      - name: Restore packages.
        run: dotnet restore Document.Validator.sln
      - name: Build Solution
        run: dotnet build Document.Validator.sln --no-restore -c ${{ env.CONFIGURATION }}
      - name: Run unit tests.
        run: dotnet test Document.Validator.sln --no-restore -c ${{ env.CONFIGURATION }} --verbosity normal

  pack_and_upload:
    needs: build_and_test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout.
        uses: actions/checkout@v4
      - name: Setup .NET.
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Restore packages.
        run: dotnet restore Document.Validator.sln
      - name: Build Solution
        run: dotnet build Document.Validator.sln --no-restore -c ${{ env.CONFIGURATION }}
      - name: Pack NuGet packages
        run: dotnet pack Document.Validator.sln --no-build -c ${{ env.CONFIGURATION }} --output ./dist/
      - name: Upload nuget packages
        uses: actions/upload-artifact@v4
        with:
          name: nuget-packages
          path: './dist'

  publish_nuget_org:
    needs: pack_and_upload
    runs-on: ubuntu-latest
    environment:
      name: NUGET_ORG
      url: 'https://www.nuget.org/profiles/masterzdran'
    steps:
      - name: Download nuget packages
        uses: actions/download-artifact@v4
        with:
          name: nuget-packages
          path: './dist'
      - name: Publish nuget.org
        run: |
          dotnet nuget push "dist/*.nupkg" --api-key ${{ secrets.NUGET_ORG_TOKEN }} --source https://api.nuget.org/v3/index.json || true
          dotnet nuget push "dist/*.snupkg" --api-key ${{ secrets.NUGET_ORG_TOKEN }} --source https://api.nuget.org/v3/index.json || true
