name: Build And Deploy all Libraries

on:
  push:    
    branches: 
      - 'release/all/**'

env:
  CONFIGURATION: 'Release'
  DOTNET_VERSION: '10.x'

jobs:
  build_test_and_pack:
    runs-on: windows-latest

    steps:
      - name: Checkout.
        uses: actions/checkout@v4
      - name: Setup .NET.
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Restore packages.
        run: dotnet restore Document.Validator.sln
      - name: Build Solution
        run: dotnet build Document.Validator.sln --no-restore -c ${{ env.CONFIGURATION }}
      - name: Run unit tests.
        run: dotnet test Document.Validator.sln --no-restore -c ${{ env.CONFIGURATION }} --verbosity normal
      - name: Pack NuGet packages
        run: dotnet pack Document.Validator.sln --no-build -c ${{ env.CONFIGURATION }} --output ./dist/
      - name: Upload nuget packages
        uses: actions/upload-artifact@v4
        with:
          name: nuget-packages
          path: './dist'

  publish_nuget_org:
    needs: build_test_and_pack
    runs-on: ubuntu-latest
    environment:
      name: NUGET_ORG
      url: 'https://www.nuget.org/profiles/masterzdran'
    steps:
      - name: Download nuget packages
        uses: actions/download-artifact@v4
        with:
          name: nuget-packages
          path: './dist'
      - name: Publish nuget.org
        run: dotnet nuget push dist/*.nupkg --api-key ${{secrets.NUGET_ORG_TOKEN}} --source https://api.nuget.org/v3/index.json
